version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: pg
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postdb
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: accept_test
    env_file:
      - local.env
    environment:
      - DB_HOST=postgres
    links:
      - postgres
